let adminCategoryList = [];
function categoryPayload() { return { nome: categoryName.value.trim(), descricao: categoryDescription.value.trim() || null, ativo: categoryActive.checked }; }
function renderCategories() { categoriesTable.innerHTML = adminCategoryList.length ? `<div class="admin-table-scroll"><table class="admin-table"><thead><tr><th>Categoria</th><th>Descrição</th><th>Status</th><th>Ações</th></tr></thead><tbody>${adminCategoryList.map((item) => `<tr><td class="admin-category-name">${Admin.escape(item.nome)}<small class="admin-muted">#${item.id}</small></td><td class="admin-category-description">${Admin.escape(item.descricao || "-")}</td><td><span class="${item.ativo ? "admin-active" : "admin-inactive"}">${item.ativo ? "Ativa" : "Inativa"}</span></td><td><button class="admin-action" data-edit-category="${item.id}">Editar</button> <button class="admin-action danger" data-delete-category="${item.id}">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : `<div class="admin-empty"><strong>Nenhuma categoria cadastrada</strong>Crie uma categoria para começar.</div>`; categoriesTable.querySelectorAll("[data-edit-category]").forEach((button) => button.addEventListener("click", () => editCategory(button.dataset.editCategory))); categoriesTable.querySelectorAll("[data-delete-category]").forEach((button) => button.addEventListener("click", () => removeCategory(button.dataset.deleteCategory))); }
async function refreshCategories() { try { adminCategoryList = await api.getCategories(); renderCategories(); } catch (error) { categoriesTable.innerHTML = `<div class="admin-empty">${Admin.escape(error.message)}</div>`; } }
function resetCategory() { categoryForm.reset(); categoryId.value = ""; categoryActive.checked = true; categoryModalTitle.textContent = "Nova categoria"; categorySave.textContent = "Salvar categoria"; }
async function editCategory(id) { try { const item = await api.getCategory(id); categoryId.value = item.id; categoryName.value = item.nome; categoryDescription.value = item.descricao || ""; categoryActive.checked = item.ativo; categoryModalTitle.textContent = "Editar categoria"; categorySave.textContent = "Salvar alterações"; Admin.modal("categoryModal"); } catch (error) { Admin.toast(error.message, true); } }
async function removeCategory(id) { if (!confirm("Tem certeza que deseja excluir esta categoria?")) return; try { await api.deleteCategory(id); Admin.toast("Categoria excluída com sucesso."); refreshCategories(); window.AdminProducts?.refresh(); } catch (error) { Admin.toast(error.message, true); } }
document.addEventListener("DOMContentLoaded", () => { newCategory.addEventListener("click", () => { resetCategory(); Admin.modal("categoryModal"); }); categoryForm.addEventListener("submit", async (event) => { event.preventDefault(); if (!categoryForm.reportValidity()) return; const id = categoryId.value; Admin.loading(categorySave, true, id ? "Salvar alterações" : "Salvar categoria"); try { if (id) await api.updateCategory(id, categoryPayload()); else await api.createCategory(categoryPayload()); Admin.modal("categoryModal", false); Admin.toast(id ? "Categoria atualizada com sucesso." : "Categoria criada com sucesso."); refreshCategories(); window.AdminProducts?.refresh(); } catch (error) { Admin.toast(error.message, true); } finally { Admin.loading(categorySave, false, id ? "Salvar alterações" : "Salvar categoria"); } }); });
window.AdminCategories = { refresh: refreshCategories };
