let adminOrderStatus = ""; let adminOrderPage = 1; let selectedOrder = null;
function orderRow(item) { return `<tr class="clickable" data-open-order="${item.id}"><td class="admin-order-id">#${item.id}</td><td class="admin-customer"><strong>${Admin.escape(item.nomeCliente)}</strong></td><td class="admin-price">${Admin.money(item.valorTotal)}</td><td>${Admin.escape(item.formaPagamento)}</td><td><span class="status-badge status-${item.status}">${Admin.status(item.status)}</span></td><td>${Admin.date(item.criadoEm)}</td><td><button class="admin-action" data-open-order="${item.id}">Detalhes</button> <button class="admin-action danger" data-delete-order="${item.id}">Excluir</button></td></tr>`; }
async function refreshOrders() { try { const result = await api.getOrdersPage({ status: adminOrderStatus, page: adminOrderPage, limit: 10 }); const items = result.data || []; ordersTable.innerHTML = items.length ? `<div class="admin-table-scroll"><table class="admin-table"><thead><tr><th>ID</th><th>Cliente</th><th>Total</th><th>Pagamento</th><th>Status</th><th>Data</th><th>Ações</th></tr></thead><tbody>${items.map(orderRow).join("")}</tbody></table></div>` : `<div class="admin-empty"><strong>Nenhum pedido encontrado</strong>Não há pedidos neste filtro.</div>`; ordersTable.querySelectorAll("[data-open-order]").forEach((button) => button.addEventListener("click", (event) => { event.stopPropagation(); openOrder(button.dataset.openOrder); })); ordersTable.querySelectorAll("[data-delete-order]").forEach((button) => button.addEventListener("click", (event) => { event.stopPropagation(); removeOrder(button.dataset.deleteOrder); })); const total = result.meta.totalPages || 1; ordersPagination.innerHTML = `<div class="admin-pagination"><button id="previousOrders" ${adminOrderPage <= 1 ? "disabled" : ""}>←</button> Página ${adminOrderPage} de ${total} <button id="nextOrders" ${adminOrderPage >= total ? "disabled" : ""}>→</button></div>`; previousOrders.onclick = () => { adminOrderPage--; refreshOrders(); }; nextOrders.onclick = () => { adminOrderPage++; refreshOrders(); }; } catch (error) { ordersTable.innerHTML = `<div class="admin-empty">${Admin.escape(error.message)}</div>`; } }
function renderOrderDetails(item) { return `<div class="detail-grid"><div class="detail-block"><h4>Cliente</h4><p><strong>${Admin.escape(item.nomeCliente)}</strong></p></div><div class="detail-block"><h4>Endereço</h4><p>${Admin.escape(item.endereco)}, ${Admin.escape(item.numero)}${item.complemento ? `, ${Admin.escape(item.complemento)}` : ""}<br>${Admin.escape(item.bairro)}</p></div></div><div class="detail-block"><h4>Produtos</h4><div class="detail-items">${(item.itens || []).map((line) => `<div class="detail-item"><span>${line.quantidade}x ${Admin.escape(line.nomeProduto)}<small class="admin-muted">${Admin.money(line.precoUnitario)} cada</small></span><strong>${Admin.money(line.subtotal)}</strong></div>`).join("")}</div></div><div class="detail-total"><span>Produtos ${Admin.money(item.valorProdutos)} + entrega ${Admin.money(item.taxaEntrega)}</span><span>${Admin.money(item.valorTotal)}</span></div><div class="detail-grid"><div class="detail-block"><h4>Pagamento</h4><p>${Admin.escape(item.formaPagamento)}</p></div><div class="detail-block"><h4>Observação</h4><p>${Admin.escape(item.observacao || "Nenhuma")}</p></div></div><div class="detail-status"><select id="detailStatus"><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="preparing">Preparing</option><option value="out_for_delivery">Out for delivery</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select><button class="btn btn-primary" id="saveStatus">Atualizar status</button></div>`; }
async function openOrder(id) { try { selectedOrder = await api.getOrder(id); orderModalTitle.textContent = `Pedido #${selectedOrder.id}`; orderDetails.innerHTML = orderDetailsMarkup(selectedOrder); detailStatus.value = selectedOrder.status; saveStatus.onclick = updateStatus; Admin.modal("orderModal"); } catch (error) { Admin.toast(error.message, true); } }
function orderDetailsMarkup(item) { return renderOrderDetails(item); }
async function updateStatus() { const button = document.getElementById("saveStatus"); Admin.loading(button, true, "Atualizar status"); try { selectedOrder = await api.updateOrderStatus(selectedOrder.id, detailStatus.value); orderDetails.innerHTML = orderDetailsMarkup(selectedOrder); detailStatus.value = selectedOrder.status; saveStatus.onclick = updateStatus; Admin.toast("Status atualizado com sucesso."); refreshOrders(); loadDashboard(); } catch (error) { Admin.toast(error.message, true); } finally { Admin.loading(button, false, "Atualizar status"); } }
async function removeOrder(id) { if (!confirm("Tem certeza que deseja excluir este pedido?")) return; try { await api.deleteOrder(id); Admin.toast("Pedido excluído com sucesso."); refreshOrders(); loadDashboard(); } catch (error) { Admin.toast(error.message, true); } }
document.addEventListener("DOMContentLoaded", () => orderFilters.addEventListener("click", (event) => { const button = event.target.closest("[data-status]"); if (!button) return; document.querySelectorAll("#orderFilters button").forEach((item) => item.classList.remove("active")); button.classList.add("active"); adminOrderStatus = button.dataset.status; adminOrderPage = 1; refreshOrders(); }));
window.AdminOrders = { refresh: refreshOrders, open: openOrder };
