let adminProducts = []; let adminCategories = [];
function productPayload() { const payload = new FormData(); payload.append("nome", productName.value.trim()); payload.append("descricao", productDescription.value.trim()); payload.append("preco", productPrice.value); payload.append("categoriaId", productCategory.value); payload.append("disponivel", String(productAvailable.checked)); payload.append("destaque", String(productFeatured.checked)); if (productImageFile.files[0]) payload.append("imagem", productImageFile.files[0]); else if (productImageUrl.value.trim()) payload.append("imagem", productImageUrl.value.trim()); return payload; }
function productOptions() { productCategory.innerHTML = `<option value="">Selecione</option>${adminCategories.map((item) => `<option value="${item.id}">${Admin.escape(item.nome)}</option>`).join("")}`; productFilter.innerHTML = `<option value="">Todas as categorias</option>${adminCategories.map((item) => `<option value="${item.id}">${Admin.escape(item.nome)}</option>`).join("")}`; }
function renderProducts() { productsTable.innerHTML = adminProducts.length ? `<div class="admin-table-scroll"><table class="admin-table"><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Disponibilidade</th><th>Destaque</th><th>Ações</th></tr></thead><tbody>${adminProducts.map((item) => `<tr><td><img class="admin-product-image" src="${Admin.escape(item.imagem || "")}" alt=""><span class="admin-product-name">${Admin.escape(item.nome)}</span><small class="admin-muted">#${item.id}</small></td><td>${Admin.escape(item.categoria?.nome || "-")}</td><td class="admin-price">${Admin.money(item.preco)}</td><td class="${item.disponivel ? "admin-available" : "admin-unavailable"}">${item.disponivel ? "Disponível" : "Indisponível"}</td><td class="admin-star">${item.destaque ? "★" : "☆"}</td><td><button class="admin-action" data-edit-product="${item.id}">Editar</button> <button class="admin-action danger" data-delete-product="${item.id}">Excluir</button></td></tr>`).join("")}</tbody></table></div>` : `<div class="admin-empty"><strong>Nenhum produto encontrado</strong>Crie um produto ou ajuste o filtro.</div>`; productsTable.querySelectorAll("[data-edit-product]").forEach((button) => button.addEventListener("click", () => editProduct(button.dataset.editProduct))); productsTable.querySelectorAll("[data-delete-product]").forEach((button) => button.addEventListener("click", () => removeProduct(button.dataset.deleteProduct))); }
async function refreshProducts() { try { adminCategories = await api.getCategories(); productOptions(); const params = { page: 1, limit: 100, search: productSearch.value.trim() }; const category = adminCategories.find((item) => String(item.id) === productFilter.value); if (category) params.category = category.nome; const firstPage = await api.getProductsPage(params); adminProducts = firstPage.data || []; for (let page = 2; page <= (firstPage.meta.totalPages || 1); page += 1) { const nextPage = await api.getProductsPage({ ...params, page }); adminProducts.push(...(nextPage.data || [])); } renderProducts(); } catch (error) { productsTable.innerHTML = `<div class="admin-empty">${Admin.escape(error.message)}</div>`; } }
function resetProduct() { productForm.reset(); productId.value = ""; productAvailable.checked = true; productModalTitle.textContent = "Novo produto"; productSave.textContent = "Salvar produto"; }
async function editProduct(id) { try { adminCategories = await api.getCategories(); productOptions(); const item = await api.getProduct(id); productId.value = item.id; productName.value = item.nome; productDescription.value = item.descricao || ""; productPrice.value = item.preco; productImageUrl.value = item.imagem || ""; productImageFile.value = ""; productCategory.value = item.categoriaId; productAvailable.checked = item.disponivel; productFeatured.checked = item.destaque; productModalTitle.textContent = "Editar produto"; productSave.textContent = "Salvar alterações"; Admin.modal("productModal"); } catch (error) { Admin.toast(error.message, true); } }
async function removeProduct(id) { if (!confirm("Tem certeza que deseja excluir este produto?")) return; try { await api.deleteProduct(id); Admin.toast("Produto excluído com sucesso."); refreshProducts(); } catch (error) { Admin.toast(error.message, true); } }
document.addEventListener("DOMContentLoaded", () => { newProduct.addEventListener("click", async () => { resetProduct(); await refreshProducts(); Admin.modal("productModal"); }); productSearch.addEventListener("input", refreshProducts); productFilter.addEventListener("change", refreshProducts); reloadProducts.addEventListener("click", refreshProducts); productForm.addEventListener("submit", async (event) => { event.preventDefault(); if (!productForm.reportValidity()) return; const id = productId.value; Admin.loading(productSave, true, id ? "Salvar alterações" : "Salvar produto"); try { if (id) await api.updateProduct(id, productPayload()); else await api.createProduct(productPayload()); Admin.modal("productModal", false); Admin.toast(id ? "Produto atualizado com sucesso." : "Produto criado com sucesso."); refreshProducts(); loadDashboard(); } catch (error) { Admin.toast(error.message, true); } finally { Admin.loading(productSave, false, id ? "Salvar alterações" : "Salvar produto"); } }); });
window.AdminProducts = { refresh: refreshProducts };
